export const packAmbiences = [
    "Aquatic.mp3",
    "Autumn.mp3",
    "Blizzard.mp3",
    "Breakfast.mp3",
    "Bug.mp3",
    "Candy.mp3",
    "Combat.mp3",
    "Dinner.mp3",
    "Dino.mp3",
    "Egyptian.mp3",
    "Elemental.mp3",
    "Gemstone.mp3",
    "Ice Monster.mp3",
    "Lunch.mp3",
    "Magic.mp3",
    "Medieval.mp3",
    "Music.mp3",
    "Pirate.mp3",
    "Retro.mp3",
    "Sci-Fi.mp3",
    "Space.mp3",
    "Spooky.mp3",
    "Sports.mp3",
    "Summer.mp3",
    "Video Game.mp3",
    "Wonderland.mp3",
    "Time.mp3",
    "Outback.mp3",
    "Bot.mp3",
    "Science.mp3",
    "Safari.mp3"
];
